# Generated by Django 6.0.6 on 2026-09-28 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudencomienda',
            name='producto',
        ),
        migrations.AddField(
            model_name='local',
            name='catalogo_pdf',
            field=models.FileField(blank=True, upload_to='catalogos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
